### PR TITLE
Implement SSH Tunneling

### PR DESCRIPTION
**Pull request by 0x15f**
This PR implements the option for SSH tunneling for the MySQL connection. It's incredibly useful for tapping databases hosted on platforms like AWS that are protected from public access. 

- The `README.md` has been updated with new configuration parameters.
- New dependencies have been added to `setup.py`
- Version has been bumped

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @0x15f, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by 0x15f** [comment]
PyCharm reformatted the file as well.

**Comment by cmerrick** [comment]
You did it @0x15f!

Thank you for signing the Singer Contribution License Agreement.

**Comment by 0x15f** [comment]
CLA has been signed.

**Comment by kaustav98255** [comment]
Hiii guys,
Do you know when this PR will be merged to the main branch and available on the Stitch UI?


Cheers
Kaustav.

**Comment by 0x15f** [comment]
Bumping this, this is the only thing preventing one of my clients from migrating all the Stitch stuff we run locally to use the Stitch UI.

**Comment by macleodmac** [comment]
Also keen for this to be merged before we can adopt it.

**Comment by 0x15f** [comment]
@cmerrick

**Comment by ebeale-stitch** [comment]
Hey @0x15f and @macleodmac !

Stitch currently supports SSH connections for MySQL.

Please see this relevant [documentation](https://www.stitchdata.com/docs/account-security/data-encryption/setting-up-ssh-tunnel-for-database-connection)!

If you run into any issues, hit up our Support team via in-app chat or at stitchsupport@talend.com

Best,

**Comment by cmerrick** [comment]
Thanks for this contribution. We feel that SSH tunneling is best implemented outside of the tap since it is useful for many taps and can be implemented generically. This is exactly what we have done at Stitch, but we haven't yet open-sourced functionality because it ties into some proprietary code. It's something we'll be looking to do in the future, however.

**Pull request closed without merging**
